# Workflow to deploy with IG Publisher and Shorthand to the hl7austria.github.io repository

name: PublishIG

# Run on updates to the master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install NPM
      uses: actions/setup-node@v2.1.2
      with:
        check-lastest: true
